### ISSUE TITLE
Program stops after Proxy window without any error

### ISSUE THREAD

**Issue by garikello3d** [ogarcia/pkgbuilds#15]
Installed _configuradorfnmt_ and tried to run it from console. First it offers to setup a proxy, which I think is ok. 

![image](https://github.com/ogarcia/pkgbuilds/assets/3742142/404f79fd-536b-4417-8887-48d5836f6576)

After I press _OK_ it just stops without any error message.
My _archlinux-java status_ gives __java-17-openjdk (default)__.

The output:
```
$ configuradorfnmt
Nov 24, 2023 1:32:55 AM es.gob.fnmt.cert.certrequest.CertRequest <clinit>
INFO: Modo de depuracion desactivado
Nov 24, 2023 1:32:55 AM es.gob.fnmt.cert.certrequest.CertRequest main
INFO: Version actual de la aplicacion: '4.0.2'
Nov 24, 2023 1:32:55 AM es.gob.fnmt.cert.certrequest.CertRequest main
INFO: La aplicacion se esta ejecutando desde /usr/share/java/configuradorfnmt/configuradorfnmt.jar
Nov 24, 2023 1:32:55 AM es.gob.fnmt.cert.certrequest.CertRequest printSystemInfo
INFO: Aplicacion FNMT de solicitud de certificados version 4.0.2.
 Sistema operativo: Linux.
 Version del sistema operativo: 6.6.1-arch1-1.
 Version de Java: 17.0.9.
 Arquitectura del JRE: 64 bits.
 Fabricante de la JVM: Oracle Corporation.
 Idioma por defecto: en_GB.
 Tamano actual en memoria: 124MB.
 Tamano maximo de memoria: 1982MB.
 Memoria actualmente libre: 109MB.
java.net.BindException: Permission denied
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194)
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:107)
	at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1426)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:330)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:389)
	at com.github.markusbernhardt.proxy.search.wpad.dhcp.DHCPSocket.<init>(DHCPSocket.java:62)
	at com.github.markusbernhardt.proxy.search.wpad.WpadProxySearchStrategy.checkDhcpAckForPAC(WpadProxySearchStrategy.java:213)
	at com.github.markusbernhardt.proxy.search.wpad.WpadProxySearchStrategy.detectScriptUrlPerDHCP(WpadProxySearchStrategy.java:193)
	at com.github.markusbernhardt.proxy.search.wpad.WpadProxySearchStrategy.getProxySelector(WpadProxySearchStrategy.java:70)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:303)
	at es.gob.fnmt.cert.certrequest.ProxyUtil.setDefaultProxy(ProxyUtil.java:75)
	at es.gob.fnmt.cert.certrequest.ProxyUtil.setProxySettings(ProxyUtil.java:203)
	at es.gob.fnmt.cert.certrequest.CertRequest.main(CertRequest.java:171)
Nov 24, 2023 1:32:59 AM es.gob.fnmt.cert.certrequest.ProxyUtil setDefaultProxy
INFO: No se usara proxy para las conexiones de red
Nov 24, 2023 1:32:59 AM es.gob.fnmt.cert.certrequest.afirma.core.misc.http.UrlHttpManager setTrustManager
INFO: Instalado correctamente el gestor de confianza SSL
Nov 24, 2023 1:32:59 AM es.gob.fnmt.cert.certrequest.afirma.core.misc.http.UrlHttpManager <clinit>
INFO: Establecido el gestor a medida de la confianza SSL
Nov 24, 2023 1:33:00 AM es.gob.fnmt.cert.certrequest.util.CustomTrustManager checkServerTrusted
INFO: Verificado correctamente el certificado SSL 'www.sede.fnmt.gob.es' contra la CA 'AC Componentes Informáticos'
Nov 24, 2023 1:33:00 AM es.gob.fnmt.cert.certrequest.Updater lambda$checkForUpdates$2
INFO: Se ha encontrado instalada la ultima version disponible del programa
Nov 24, 2023 1:33:01 AM es.gob.fnmt.cert.certrequest.DerbyPrivateKeyDaoV3 open
INFO: Base de datos abierta (V2): org.apache.derby.impl.jdbc.EmbedConnection@586831282 (XID = 384), (SESSIONID = 1), (DATABASE = FnmtKeysV2), (DRDAID = null) 

```

So there is nothing useful in this log, the exitcode of a program is 0.
If we look into `strace -f configuradorfnmt` we can see that it tries to open a bunch of files that it cannot find (with `NOENT`), but it's not clear whether they are critical or not.

**Comment by ogarcia** [comment]
The _configuradorfnmt_ is not intended to be run directly. It is when you enter the _fnmt website_ and do the process of requesting a certificate when at a given moment it is executed from the browser to make the signature. If you run it directly, the only thing it allows you to do is to configure the connection (what you have seen of the proxy).
